### ISSUE TITLE
fatal: empty ident name (for <user@server.(none)>) not allowed

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#4] opened 2013-08-02 21:16 UTC
I have set a git identity:

git config-l
user.name=My Name
user.email=my.name@foo.com

When running build_kernel.sh I get an error

fatal: empty ident name (for <user@server.(none)>) not allowed
You need to set your committer info first
git tree is clean...

**\* Please tell me who you are.
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

Why should a build script care about my identity?
Why does it require something already known?

**Comment by RobertCNelson** [comment] 2013-08-02 21:33
Sure blame the messenger.. ;)  The build script and I do not care about your identity.  That's one reason when the script recognizes an empty config it gives you the fake user/email:
https://github.com/RobertCNelson/stable-kernel/blob/master/scripts/git.sh#L170

The issue is; this script uses 'git', specifically "git am <patch>" and starting at some point with the v1.8.x tree it is now much more picky about user.name/user.email...

So, moving forward, if you'd like to use my build scripts, just follow along, otherwise go complain to: http://git-scm.com/

So, closing as I can't do anything about it... ;)

Regards,

**Closed as completed by RobertCNelson** 2013-08-02 21:33 UTC
